site_name: Calculation Docs

site_url: https://mwwilcox.github.io/calculator

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tags
    - navigation.sections
    - navigation.top

# hide:
#   - navigation
#   - toc

plugins:
  - mkdocstrings
  - search

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
